CREATE TABLE IF NOT EXISTS students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  course INT NOT NULL,
  grades TEXT NOT NULL DEFAULT '[]',
  email VARCHAR(255) NOT NULL,
  image VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS migrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hash VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
